[project]
name = "vestas-risk-case"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
    "ipywidgets>=8.1.9",
    "langchain>=1.4.0",
    "langchain-core>=1.6.3",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "pymupdf4llm>=1.28.2",
    "python-dotenv>=1.2.3",
    "tqdm>=4.70.1",
]
